server:
  servlet:
    context-path: /axon-102

spring:
  application:
    name: axon-102
  main:
    banner-mode: "off"
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=Oracle
    username: axon102
    password: axon102
    driver-class-name: org.h2.Driver

axon:
  serializer:
    events: jackson
    general: jackson
    messages: jackson
